# Generated by Django 3.2.21 on 2023-10-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='description',
            field=models.TextField(),
        ),
    ]
